/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.linkviewer.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long tgId;
    private OffsetDateTime createdAt;

    public Users() {}

    public Users(Users value) {
        this.tgId = value.tgId;
        this.createdAt = value.createdAt;
    }

    @ConstructorProperties({ "tgId", "createdAt" })
    public Users(
        @NotNull Long tgId,
        @NotNull OffsetDateTime createdAt
    ) {
        this.tgId = tgId;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>LINKVIEWER.USERS.TG_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgId() {
        return this.tgId;
    }

    /**
     * Setter for <code>LINKVIEWER.USERS.TG_ID</code>.
     */
    public void setTgId(@NotNull Long tgId) {
        this.tgId = tgId;
    }

    /**
     * Getter for <code>LINKVIEWER.USERS.CREATED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>LINKVIEWER.USERS.CREATED_AT</code>.
     */
    public void setCreatedAt(@NotNull OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.tgId == null) {
            if (other.tgId != null)
                return false;
        }
        else if (!this.tgId.equals(other.tgId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tgId == null) ? 0 : this.tgId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(tgId);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
