app:
  telegram-token: ${TELEGRAM_TOKEN}

api:
  scrapper:
    baseUrl: http://localhost:8080/

client:
  retry:
    initial-interval: 5s
    max-attempts: 5
    max-interval: 10s
    multiplier: 2
    codes: 500, 501, 502, 503 ,504
  backoff: linear

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

spring:
  config:
    import: classpath:/env.properties
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
