/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.linkviewer;


import edu.java.scrapper.domain.jooq.linkviewer.tables.Gitcommits;
import edu.java.scrapper.domain.jooq.linkviewer.tables.Links;
import edu.java.scrapper.domain.jooq.linkviewer.tables.Userlink;
import edu.java.scrapper.domain.jooq.linkviewer.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in LINKVIEWER.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>LINKVIEWER.GITCOMMITS</code>.
     */
    public static final Gitcommits GITCOMMITS = Gitcommits.GITCOMMITS;

    /**
     * The table <code>LINKVIEWER.LINKS</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>LINKVIEWER.USERLINK</code>.
     */
    public static final Userlink USERLINK = Userlink.USERLINK;

    /**
     * The table <code>LINKVIEWER.USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
