/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.linkviewer.tables.records;


import edu.java.scrapper.domain.jooq.linkviewer.tables.Userlink;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserlinkRecord extends TableRecordImpl<UserlinkRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKVIEWER.USERLINK.USER_ID</code>.
     */
    public void setUserId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKVIEWER.USERLINK.USER_ID</code>.
     */
    @Nullable
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINKVIEWER.USERLINK.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKVIEWER.USERLINK.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Userlink.USERLINK.USER_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return Userlink.USERLINK.LINK_ID;
    }

    @Override
    @Nullable
    public Long component1() {
        return getUserId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Long value1() {
        return getUserId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public UserlinkRecord value1(@Nullable Long value) {
        setUserId(value);
        return this;
    }

    @Override
    @NotNull
    public UserlinkRecord value2(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public UserlinkRecord values(@Nullable Long value1, @Nullable Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserlinkRecord
     */
    public UserlinkRecord() {
        super(Userlink.USERLINK);
    }

    /**
     * Create a detached, initialised UserlinkRecord
     */
    @ConstructorProperties({ "userId", "linkId" })
    public UserlinkRecord(@Nullable Long userId, @Nullable Long linkId) {
        super(Userlink.USERLINK);

        setUserId(userId);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserlinkRecord
     */
    public UserlinkRecord(edu.java.scrapper.domain.jooq.linkviewer.tables.pojos.Userlink value) {
        super(Userlink.USERLINK);

        if (value != null) {
            setUserId(value.getUserId());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }
}
