/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.linkviewer.tables;


import edu.java.scrapper.domain.jooq.linkviewer.Linkviewer;
import edu.java.scrapper.domain.jooq.linkviewer.tables.records.StackoverflowanswersRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Stackoverflowanswers extends TableImpl<StackoverflowanswersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINKVIEWER.STACKOVERFLOWANSWERS</code>
     */
    public static final Stackoverflowanswers STACKOVERFLOWANSWERS = new Stackoverflowanswers();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<StackoverflowanswersRecord> getRecordType() {
        return StackoverflowanswersRecord.class;
    }

    /**
     * The column <code>LINKVIEWER.STACKOVERFLOWANSWERS.NAME</code>.
     */
    public final TableField<StackoverflowanswersRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>LINKVIEWER.STACKOVERFLOWANSWERS.ANSWER_ID</code>.
     */
    public final TableField<StackoverflowanswersRecord, Long> ANSWER_ID = createField(DSL.name("ANSWER_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>LINKVIEWER.STACKOVERFLOWANSWERS.QUESTION_ID</code>.
     */
    public final TableField<StackoverflowanswersRecord, Long> QUESTION_ID = createField(DSL.name("QUESTION_ID"), SQLDataType.BIGINT, this, "");

    private Stackoverflowanswers(Name alias, Table<StackoverflowanswersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Stackoverflowanswers(Name alias, Table<StackoverflowanswersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINKVIEWER.STACKOVERFLOWANSWERS</code> table
     * reference
     */
    public Stackoverflowanswers(String alias) {
        this(DSL.name(alias), STACKOVERFLOWANSWERS);
    }

    /**
     * Create an aliased <code>LINKVIEWER.STACKOVERFLOWANSWERS</code> table
     * reference
     */
    public Stackoverflowanswers(Name alias) {
        this(alias, STACKOVERFLOWANSWERS);
    }

    /**
     * Create a <code>LINKVIEWER.STACKOVERFLOWANSWERS</code> table reference
     */
    public Stackoverflowanswers() {
        this(DSL.name("STACKOVERFLOWANSWERS"), null);
    }

    public <O extends Record> Stackoverflowanswers(Table<O> child, ForeignKey<O, StackoverflowanswersRecord> key) {
        super(child, key, STACKOVERFLOWANSWERS);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Linkviewer.LINKVIEWER;
    }

    @Override
    @NotNull
    public Stackoverflowanswers as(String alias) {
        return new Stackoverflowanswers(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Stackoverflowanswers as(Name alias) {
        return new Stackoverflowanswers(alias, this);
    }

    @Override
    @NotNull
    public Stackoverflowanswers as(Table<?> alias) {
        return new Stackoverflowanswers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Stackoverflowanswers rename(String name) {
        return new Stackoverflowanswers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Stackoverflowanswers rename(Name name) {
        return new Stackoverflowanswers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Stackoverflowanswers rename(Table<?> name) {
        return new Stackoverflowanswers(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<String, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
