/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.linkviewer;


import edu.java.scrapper.domain.jooq.DefaultCatalog;
import edu.java.scrapper.domain.jooq.linkviewer.tables.Gitcommits;
import edu.java.scrapper.domain.jooq.linkviewer.tables.Links;
import edu.java.scrapper.domain.jooq.linkviewer.tables.Userlink;
import edu.java.scrapper.domain.jooq.linkviewer.tables.Users;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Linkviewer extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINKVIEWER</code>
     */
    public static final Linkviewer LINKVIEWER = new Linkviewer();

    /**
     * The table <code>LINKVIEWER.GITCOMMITS</code>.
     */
    public final Gitcommits GITCOMMITS = Gitcommits.GITCOMMITS;

    /**
     * The table <code>LINKVIEWER.LINKS</code>.
     */
    public final Links LINKS = Links.LINKS;

    /**
     * The table <code>LINKVIEWER.USERLINK</code>.
     */
    public final Userlink USERLINK = Userlink.USERLINK;

    /**
     * The table <code>LINKVIEWER.USERS</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Linkviewer() {
        super("LINKVIEWER", null);
    }


    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Gitcommits.GITCOMMITS,
            Links.LINKS,
            Userlink.USERLINK,
            Users.USERS
        );
    }
}
